adapter_config: default
adapter_name: compacter
adaptive_learning: False
do_eval: True
do_train: True
eval_steps: 50
evaluation_strategy: steps
initial_train_dataset_size: 0.3
learning_rate: 0.00004
logging_steps: 50
logging_strategy: steps
max_seq_length: 512
max_steps: 1300
model_name_or_path: roberta-base
num_train_epochs: 3
output_dir: /content/tmp/
overwrite_output_dir: True
per_device_eval_batch_size: 16
per_device_train_batch_size: 16
query_samples_count: 256
random_seed: 1
remove_unused_columns: False
seed: 12
target_score: 87.1
task_name: mnli
test_file: /content/Rio_Marker_Tool/datasets/test.csv
train_file: /content/Rio_Marker_Tool/datasets/train.csv
type_file: csv
use_adapters: True
use_tensorboard: True
validation_file: /content/Rio_Marker_Tool/datasets/valid.csv