random_seed: 1
model_name_or_path: microsoft/mpnet-base
task_name: mnli
do_train: True
do_eval: True
max_seq_length: 512
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
learning_rate: 4e-5
overwrite_output_dir: True
output_dir: /tmp/
logging_strategy: steps
logging_steps: 50
evaluation_strategy: steps
eval_steps: 50
seed: 12
max_steps: 684
remove_unused_columns: False
num_train_epochs: 3
use_tensorboard: True
type_file: csv
train_file: C:/Users/SilviaJuzova/Documents/Rio_Marker_Tool/datasets/train.csv
validation_file: C:/Users/SilviaJuzova/Documents/Rio_Marker_Tool/datasets/valid.csv
test_file: C:/Users/SilviaJuzova/Documents/Rio_Marker_Tool/datasets/test.csv
use_adapters: True
adapter_name: compacter
adapter_config: None
adaptive_learning: False
target_score: 87.1
initial_train_dataset_size: 0.3
query_samples_count: 256